/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        cream: {
          50: 'var(--color-cream)',
          100: 'var(--color-cream-dark)',
          200: 'var(--color-border)',
        },
        burgundy: {
          50: 'var(--color-burgundy-light)',
          100: 'var(--color-cream-dark)',
          200: 'var(--color-border)',
          300: 'var(--color-burgundy-light)',
          400: 'var(--color-burgundy-light)',
          500: 'var(--color-burgundy-light)',
          600: 'var(--color-burgundy-light)',
          700: 'var(--color-burgundy)',
          800: 'var(--color-burgundy-dark)',
          900: 'var(--color-burgundy-dark)',
        },
        gold: {
          50: 'var(--color-cream-dark)',
          100: 'var(--color-border)',
          200: 'var(--color-border)',
          300: 'var(--color-gold-light)',
          400: 'var(--color-gold-light)',
          500: 'var(--color-gold)',
          600: 'var(--color-gold)',
          700: 'var(--color-gold)',
          800: 'var(--color-burgundy-dark)',
          900: 'var(--color-burgundy-dark)',
        },
        gray: {
          400: 'var(--color-text-light)',
          500: 'var(--color-text-light)',
          600: 'var(--color-text-light)',
          800: 'var(--color-text)',
          900: 'var(--color-text)',
        },
        academic: {
          bg: '#FAFAF8',
          sidebar: '#F5F3EF',
          border: '#E8E4DC',
          text: '#2D2D2D',
          muted: '#5A5A5A',
        },
      },
      fontFamily: {
        'source-serif': ['var(--font-source-serif)', '"Source Serif 4"', 'Georgia', 'serif'],
        spectral: ['var(--font-spectral)', 'Spectral', 'Georgia', 'serif'],
        inter: ['var(--font-inter)', 'Inter', 'system-ui', 'sans-serif'],
      },
      typography: ({ theme }) => ({
        catholic: {
          css: {
            '--tw-prose-body': 'var(--color-text)',
            '--tw-prose-headings': 'var(--color-burgundy)',
            '--tw-prose-lead': 'var(--color-text-light)',
            '--tw-prose-links': 'var(--color-burgundy)',
            '--tw-prose-bold': 'var(--color-text)',
            '--tw-prose-counters': 'var(--color-gold)',
            '--tw-prose-bullets': 'var(--color-gold)',
            '--tw-prose-hr': 'var(--color-border)',
            '--tw-prose-quotes': 'var(--color-burgundy-dark)',
            '--tw-prose-quote-borders': 'var(--color-burgundy)',
            '--tw-prose-captions': 'var(--color-text-light)',
            '--tw-prose-th-borders': 'var(--color-border-dark)',
            '--tw-prose-td-borders': 'var(--color-border)',
            'maxWidth': 'none',
            'fontSize': '1.0625rem',
            'lineHeight': '1.95',
            'letterSpacing': '0.01em',
            'h1': {
              fontFamily: theme('fontFamily.spectral').join(', '),
              letterSpacing: '0.02em',
              fontWeight: '700',
              color: 'var(--color-burgundy-dark)',
              marginTop: '2.5em',
              marginBottom: '0.8em',
              fontSize: '1.85rem',
              lineHeight: '1.35',
              borderBottom: '2px solid var(--color-border)',
              paddingBottom: '0.5em',
            },
            'h2': {
              fontFamily: theme('fontFamily.spectral').join(', '),
              letterSpacing: '0.015em',
              fontWeight: '700',
              color: 'var(--color-burgundy)',
              marginTop: '2.5em',
              marginBottom: '0.8em',
              fontSize: '1.5rem',
              lineHeight: '1.4',
            },
            'h3': {
              fontFamily: theme('fontFamily.spectral').join(', '),
              letterSpacing: '0.01em',
              fontWeight: '600',
              color: 'var(--color-burgundy-dark)',
              marginTop: '2em',
              marginBottom: '0.6em',
              fontSize: '1.25rem',
              lineHeight: '1.45',
            },
            'p': {
              marginBottom: '1.35em',
              textAlign: 'justify',
              hyphens: 'auto',
              wordSpacing: '0.02em',
            },
            'a': {
              color: 'var(--color-burgundy)',
              textDecoration: 'underline',
              textDecorationColor: 'var(--color-burgundy-light)',
              textUnderlineOffset: '3px',
              transition: 'all 0.2s ease',
              '&:hover': {
                color: 'var(--color-burgundy-light)',
                textDecorationColor: 'var(--color-burgundy-light)',
              },
            },
            'blockquote': {
              fontStyle: 'italic',
              borderLeftWidth: '4px',
              borderLeftColor: 'var(--color-burgundy)',
              backgroundColor: 'var(--color-cream-dark)',
              padding: '1em 1.5em',
              borderRadius: '0 8px 8px 0',
              marginLeft: '0',
              marginRight: '0',
              'p:first-of-type::before': { content: 'none' },
              'p:last-of-type::after': { content: 'none' },
            },
            'table': {
              fontSize: '0.92rem',
              borderCollapse: 'collapse',
            },
            'thead': {
              borderBottomWidth: '2px',
              borderBottomColor: 'var(--color-burgundy)',
            },
            'thead th': {
              fontFamily: theme('fontFamily.spectral').join(', '),
              fontWeight: '600',
              color: 'var(--color-burgundy-dark)',
              backgroundColor: 'var(--color-cream-dark)',
              padding: '0.75em 1em',
              textAlign: 'left',
            },
            'tbody td': {
              padding: '0.75em 1em',
              borderBottomWidth: '1px',
              borderBottomColor: 'var(--color-border)',
            },
            'tbody tr': {
              '&:hover': {
                backgroundColor: 'var(--color-cream)',
              },
            },
            'strong': {
              color: 'var(--color-text)',
              fontWeight: '700',
            },
            'code': {
              color: 'var(--color-burgundy)',
              fontWeight: '500',
            },
          },
        },
      }),
    },
  },
  plugins: [
    require('@tailwindcss/typography'),
  ],
};
